# Data Loading and Storage Practical

---
1.   Start a new Jupyter Notebook

2.   Import the pandas Python package using the standard alias: `pd`

In [0]:
import pandas as pd

3.   Load the first 5 rows of the data stored in the file `data/spending_ch2_practical.csv` into a `DataFrame` named `df` using the default parameters of `read_csv` and then print `df`

In [0]:
df = pd.read_csv('data/spending_ch2_practical.csv', nrows=5)
df

4. There is a header for the data set but notice it is after a comment which takes up 1 row. Reload the first 5 rows of the data from the same file overwriting `df` but this time skip the first row.

In [0]:
df = pd.read_csv('data/spending_ch2_practical.csv', skiprows=[0], nrows=5)
df

5. It seems that the data is not comma separated as the file extension '.csv' suggests (this is a real issue you will run into), rather it looks like it is delimited using a different character. Reload the first 5 rows of the data from the same file overwriting `df` but this time also specify what the file values are separated by.

In [0]:
df = pd.read_csv('data/spending_ch2_practical.csv', skiprows=[0], sep='/', nrows=5)
df

6. Notice that in the entry at the integer location (2,2) there is the string "Na", this should be handled as a missing value. Load all of the data from the same file overwriting `df` but this time specify that "Na" should be considered as a missing value. Verify that "Na" was identified as a missing value (i.e. nan)

In [0]:
df = pd.read_csv('data/spending_ch2_practical.csv', skiprows=[0], sep='/', na_values='Na')

7. Print the `DataFrame` attribute `shape` to view the dimensions of `df`

In [0]:
df.shape

8. Since `df` is small enough we can view the entire `DataFrame`. Print `df` and scan over the `DataFrame` thinking of any other issues there may be

In [0]:
df

9. From a quick glance, it seems as though the 'unique_id' column is indeed unique for each entry. Use the `DataFrame` method `nunique` to verify this.

In [0]:
df.nunique()

10. Reload the data from the file `data/spending_ch2_practical.csv` into `df` with all the parameters we have set, but this time set the index to be the `unique_id` column

In [0]:
df = pd.read_csv('data/spending_ch2_practical.csv', skiprows=[0], sep='/', na_values='Na', index_col='unique_id')

11. Write a new file named `data/med_spending_ch2_practical.csv` which only has the `medication` and `specialty` columns saved from the data in `df`

In [0]:
df.loc[:, ['medication', 'specialty']].to_csv('data/med_spending_ch2_practical.csv')