In [2]:
import pandas as pd

# Exercise 5.0: Importing the Honolulu Flights Data Set

For some of the exercises in this chapter we will again be working with a data set containing information about all the arriving and departing flights in and out of the Honolulu aiport, HNL, on the Island of Oahu in December 2015. This data set was introduced in chapter 3: Exploring Data 

Please run the following code cell which will parse the 'honolulu_flights.csv' file, and build the `HNL_flights_df DataFrame` before trying the exercises in this chapter related to the Honolulu flights data set.

Pleases recall that this data set contains the following columns:

| Column |Description|
|:----------|-----------|
| `YEAR` | The year of the flight  |
| `MONTH` |  The month of the flight |
| `DAY` |  The day of the flight |
| `DAY_OF_WEEK` |  The day of the week of the flight |
| `FLIGHT_NUMBER` |  The flight number of the flight |
| `ORIGIN_AIRPORT` |  The origin airport of the flight  |
| `DESTINATION_AIRPORT` |  The destination airport of the flight |
| `DEPARTURE_DELAY` |  The departure delay of the flight  |
| `DISTANCE` |  The distance of the flight in miles |
| `AIR_TIME` |  The flight time without taxiing in minutes |
| `ARRIVAL_DELAY` |  The arrival delay of the flight  |

In [3]:
HNL_flights_df = pd.read_csv('Data/honolulu_flights.csv')

# Exercise 5.1: Inspecting and Modifying Data Types

 Consider the following `DataFrame`
 
```python
scoring_2018 = pd.DataFrame({'Rank': {'Tennessee Tech': 1, 'Morehead St.': 2, 'Texas Tech': 3},
                                'G': {'Tennessee Tech': 65, 'Morehead St.': 63, 'Texas Tech': 65},
                              'W.L': {'Tennessee Tech': '53-12','Morehead St.': '37-26','Texas Tech': '45-20'},
                                'R': {'Tennessee Tech': 639, 'Morehead St.': 529, 'Texas Tech': 529},
                               'PG': {'Tennessee Tech': 9.8, 'Morehead St.': 8.4, 'Texas Tech': 8.1}})
```

Which table correctly states the data type of the columns of `scoring_2018` in its currect state?


A: 

| Column |Data Type|
|:----------|-----------|
| `Rank` |  int64 |
| `G` |  int64 |
| `W.L` |   object |
| `R` |  int64 |
| `PG` |  float64 |

B: 

| Column |Data Type|
|:----------|-----------|
| `Rank` |  object |
| `G` |  int64 |
| `W.L` |   object |
| `R` |  int64 |
| `PG` |  object |

C:  

| Column |Data Type|
|:----------|-----------|
| `Rank` |  object |
| `G` |  object |
| `W.L` |   object |
| `R` |  object |
| `PG` |  object |


**Correct Answer**

A:

| Column |Data Type|
|:----------|-----------|
| `Rank` |  int64 |
| `G` |  int64 |
| `W.L` |   object |
| `R` |  int64 |
| `PG` |  float64 |

**Explanation**

The data types of a `DataFrame` can be inspected by accessing the `dtypes` attribute. The solution to this exercise can be found by observing the output of the following command:

```python
>>> scoring_2018.dtypes
Rank      int64
G         int64
W.L      object
R         int64
PG      float64
dtype: object
```

---


Which line(s) of code will modify the data types of `scoring_2018`, inplace, so that it matches the following table?

| Column |Data Type|
|:----------|-----------|
| `Rank` |  object |
| `G` |  object |
| `W.L` |   object |
| `R` |  object |
| `PG` |  object |

A.
```python
scoring_2018['Rank'] = scoring_2018['Rank'].astype('object')
scoring_2018['G'] = scoring_2018['G'].astype('object')
scoring_2018['R'] = scoring_2018['R'].astype('object')
scoring_2018['PQ'] = scoring_2018['PG'].astype('object')
```

B.
```python
scoring_2018 = scoring_2018[['Rank', 'G',  'R', 'PG']].astype('object')
```

C. 
```python
scoring_2018 = scoring_2018.astype('object')
```

D. 

All of the above

**Correct Answer**

D. 

All of the above

**Explanation**

Try running all of the options in the scratch code cell and you will see that they are all valid.

# Exercise 5.2: `Series` String Methods

Given the  `Series`, `UH_Series` which can be described by the following table:

| Index |Data |
|:----------|-----------|
| 0 | 'U H Manoa' |
| 1 | 'UH_Manoa' |
| 2 | 'UH Manoa' |
| 3 | 'UH-Manoa' |

And can be constructed using the code shown below:

```python
UH_Series = pd.Series(['U H Manoa',  'UH_Manoa', 'UH Manoa', 'UH-Manoa'])
```

Which line of code will modify `UH_Series`, inplace, so that each entry matches the string: 'UHManoa'?

A:
```python
(UH_Series
 .str.replace(" ", "")
 .str.replace("_","")
.str.replace("-",""))
```

B: 
```python
(UH_Series
 .str.replace("_"," ")
.str.replace("-"," "))
```

C:
```python
UH_Series = (UH_Series
 .str.replace(" ", "")
 .str.replace("_","")
.str.replace("-",""))
```

D:
```python
UH_Series = (UH_Series
 .str.replace("_","")
.str.replace("-",""))
```

*Hint: Feel free to use the code cell below to try these commands out. For the incorrect options, make note of what is going wrong and or what errors are being thrown.*

**Correct Answer**

C:
```python
UH_Series = (UH_Series
 .str.replace(" ", "")
 .str.replace("_","")
.str.replace("-",""))
```

**Explanation**

A: This option does not make the modifications inplace, i.e. the original `DataFrame` is left unchanged.

B: This option also does not make the modifications inplace, and it does not correctly replace the characters in the strings. The "_" and "-" characters should be replaced with the empty string, "", rather, it is replaced with a space, " " in this option.

C: This line of code correctly replaces the all the characters in the strings of the `Series` with empty strings.

D: The spaces in the strings are not replace with empty strings, "", as they should.

# Exercise 5.3: Reindexing

Given the following `DataFrame`, `df`, described in the table below:

|  | color | number |
|:----------|-----------|
| d | green | 4 |
| a | blue |1|
| c | orange | 3 |

And constructed using the following code:

```python
df = pd.DataFrame({'color':['green','blue', 'orange'], 'number': [4, 1, 3]}, 
                  index = ['d', 'a', 'c'])
```

Use the `reindex()` function to modify the `df DataFrame` inplace so that its new index is the list of labels `[a, b, c, d]` and the new values are filled using the forward fill method. The `DataFrame` should have the following information and structure.

|  | color | number |
|:----------|-----------|
| a | blue |1|
| b | NaN | NaN |
| c | orange | 3 |
| d | green | 4 |

**One Possible Solution**

```python
df = df.reindex(['a', 'b', 'c', 'd'])
```

# Exercise 5.4: Filtering Missing Values

Consider the `DataFrame`, `flights_df`, described using the table below:

|  | ORIGIN_AIRPORT | DESTINATION_AIRPORT | DEPARTURE_DELAY| ARRIVAL_DELAY |
|:----------|-----------|---------|
| 0 | HNL | SFO | 3.0 | -21.0 |
| 1 | LAS | HNL | NaN | -2.0 |
| 2 | HNL | ITO | NaN | NaN |
| 3 | HNL | KOA| -6.0 | -9.0 |

And constructed using the following line of code:

```python
flights_df = pd.DataFrame({'ORIGIN_AIRPORT': ['HNL', 'LAS', 'HNL', 'HNL'], 
                           'DESTINATION_AIRPORT': ['SFO', 'HNL', 'ITO', 'KOA'],
                           'DEPARTURE_DELAY': [ 3., None, None, -6.], 
                           'ARRIVAL_DELAY': [-21.,  -2.,  None,  -9.]})
```

Which of the following statements will create a `DataFrame` with that is a subset of `flights_df` containing only ***rows*** that do not have ***both*** a missing `ARRIVAL_DELAY`  and `DEPARTURE_DELAY` value? (do not modify the original `flights_df DataFrame`).

A:
```python
flights_df.dropna(axis='columns')
```

B:
```python
flights_df.dropna(axis='rows')
```

C:
```python
flights_df[ ~ (flights_df.loc[:, 'DEPARTURE_DELAY'].isnull() 
               & flights_df.loc[:, 'ARRIVAL_DELAY'].isnull())]
```

D:
```python
flights_df[ ~ (flights_df.loc[:, 'DEPARTURE_DELAY'].isnull() 
               | flights_df.loc[:, 'ARRIVAL_DELAY'].isnull())]
```

**Correct Answer**

C:
```python
flights_df[ ~ (flights_df.loc[:, 'DEPARTURE_DELAY'].isnull() 
               & flights_df.loc[:, 'ARRIVAL_DELAY'].isnull())]
```

**Explanation**

A: This line of code will drop columns that have a missing value.

B, D: These options will result in the same `DataFrame`. All the rows with missing values will be dropped from `flights_df` leaving only rows 0 and 3. Recall that '|' is the boolean operator for a logical 'OR', this problem asked to remove rows with missing values in both of the `ARRIVAL_DELAY`  and `DEPARTURE_DELAY` columns.

C: This line of code correctly filters the rows with missing values by performing a boolean operation on the results of the two calls to the  `isnull() Series` method.

# Exercise 5.5: Filling Missing Entries with Static Values

Again let us consider the `flights_df DataFrame` that was first introduced in exercise 4.4 and is described in the table below:

| index | ORIGIN_AIRPORT | DESTINATION_AIRPORT | DEPARTURE_DELAY| ARRIVAL_DELAY |
|:----------|-----------|---------|---------|---------|
| 0 | HNL | SFO | 3.0 | -21.0 |
| 1 | LAS | HNL | NaN | -2.0 |
| 2 | HNL | ITO | NaN | NaN |
| 3 | HNL | KOA| -6.0 | -9.0 |

And constructed using the following line of code:

```python
flights_df = pd.DataFrame({'ORIGIN_AIRPORT': ['HNL', 'LAS', 'HNL', 'HNL'], 
                           'DESTINATION_AIRPORT': ['SFO', 'HNL', 'ITO', 'KOA'],
                           'DEPARTURE_DELAY': [ 3., None, None, -6.], 
                           'ARRIVAL_DELAY': [-21.,  -2.,  None,  -9.]})
```

Write a command using the code cell below to fill the missing entries in both the `DEPARTURE_DELAY` and `ARRIVAL_DELAY` columns of `flights_df` with 0. The original `DataFrame` should be modified, i.e. the changes should be done in place.

**One Possible Solution**
```python
flights_df.fillna(0, inplace=True)
```

**Explanation**

Note that the only missing values in `flights_df` are in  the `DEPARTURE_DELAY` and `ARRIVAL_DELAY` columns. Furthermore, missing values in both columns are to be set to the same value, 0. Therefore, it is safe to fill all missing values in the `DataFrame` with 0. If you used a dictionary to specify the values to fill with for each column that would also be correct.

# Exercise 5.6: Filling Missing Entries with Dynamic Values

We will utilize the `flights_df DataFrame` one last time. Recall that it contains the information described in the table below:

| index | ORIGIN_AIRPORT | DESTINATION_AIRPORT | DEPARTURE_DELAY| ARRIVAL_DELAY |
|:----------|-----------|---------|---------|---------|
| 0 | HNL | SFO | 3.0 | -21.0 |
| 1 | LAS | HNL | NaN | -2.0 |
| 2 | HNL | ITO | NaN | NaN |
| 3 | HNL | KOA| -6.0 | -9.0 |

And can be constructed using the following line of code:

```python
flights_df = pd.DataFrame({'ORIGIN_AIRPORT': ['HNL', 'LAS', 'HNL', 'HNL'], 
                           'DESTINATION_AIRPORT': ['SFO', 'HNL', 'ITO', 'KOA'],
                           'DEPARTURE_DELAY': [ 3., None, None, -6.], 
                           'ARRIVAL_DELAY': [-21.,  -2.,  None,  -9.]})
```

Write a command using the code cell below to fill the missing entries in both the `DEPARTURE_DELAY` and `ARRIVAL_DELAY` columns with the column medians. The original `DataFrame` should **not** be modified.

**One Possible Solution**
```python
flights_df.fillna({'DEPARTURE_DELAY': flights_df.loc[:, 'DEPARTURE_DELAY'].median(), 
                   'ARRIVAL_DELAY': flights_df.loc[:, 'ARRIVAL_DELAY'].median()})
```